version: '3.9'

services:

  mocky_db:
    container_name: mocky_db_postgres_container
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: mockyuser
      POSTGRES_PASSWORD: mockypassword
      POSTGRES_DB: mockydb

  pgadmin:
    container_name: pgAdmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  mockybackend:
    container_name: mocky_backend_container
    image: mockybackend:latest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://mocky_db:5432/mockydb
      SPRING_DATASOURCE_USERNAME: mockyuser
      SPRING_DATASOURCE_PASSWORD: mockypassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
    depends_on:
      - mocky_db

  mocky_node_app:
    container_name: mocky_node_app_container
    image: mocky:latest
    restart: always
    build:
      context: ./../../mocky
      dockerfile: Dockerfile
    depends_on:
      - mocky_db
    ports:
      - "3333:3333"
    environment:
      - NODE_ENV=production
      - PORT=3333
    volumes:
      - ./mocky_node_app:/usr/src/app